require('user.options')
require('user.plugins')
require('user.colorscheme')
require('user.statuslines')
require('user.gitsigns')
require('user.nvim-tree')
require('user.comments')
require('user.telescope')
require('user.misc')

require('user.lsp')
